export const homeObjOne = {
    lightBg: false,
    primary: true,
    imgStart: "",
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: "Get Started",
    description: "We help busness owners increase thier revenue. purs Teams ",
    headline: "Lead Generation Specialist for Online Business",
    lightText: true,
    topLine: "Marketing Agency",
    start: "",
    img: "/images/svg-1.svg",
    alt: "image",
};

export const homeObjTwo = {
    lightBg: true,
    primary: false,
    imgStart: "start",
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: "Get Started",
    description: "We help business owners increase thier revenue. purs Teams ",
    headline: "Lead Generation Specialist for Online Business",
    lightText: false,
    topLine: "Marketing Agency",
    start: "true",
    img: "/images/profile.jpg",
    alt: "image",
};
export const homeObjTree = {
    lightBg: false,
    primary: true,
    imgStart: "",
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: "Get Started",
    description: "We help busness owners increase thier revenue. purs Teams ",
    headline: "Lead Generation Specialist for Online Business",
    lightText: true,
    topLine: "Marketing Agency",
    start: "",
    img: "/images/svg-2.svg",
    alt: "image",
};
export const homeObjFour = {
    lightBg: false,
    primary: true,
    imgStart: "start",
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: "Get Started",
    description: "We help busness owners increase thier revenue. purs Teams ",
    headline: "Lead Generation Specialist for Online Business",
    lightText: true,
    topLine: "Marketing Agency",
    start: "true",
    img: "/images/svg-3.svg",
    alt: "image",
};